repos:
    - repo: https://github.com/PyCQA/bandit
      rev: 1.6.0 # Update me!
      hooks:
        - id: bandit
          name: bandit
          exclude: tests
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: d4b887a69e6c8ae4666acc848f3dbba595a2bdf9
      hooks:
        - id: trailing-whitespace
          #         - id: flake8
          #     - repo: local
          #       hooks:
          #         - id: pylint
          #           name: pylint
          #           entry: python -m pylint.__main__ tests mst_gateway
          #           language: system
          #           types: [python]
