definitions:
 steps:
   - step: &Delete_test_branch
        name: Delete test branch from poject
        script:
         - destfolder="$BITBUCKET_WORKSPACE/$BITBUCKET_DEPLOYMENT_ENVIRONMENT/$BITBUCKET_REPO_SLUG"
         - echo "[[ -d $destfolder ]] || exit 0; cd $destfolder" > run.sh
         - echo "cat > local_run_$BITBUCKET_DEPLOYMENT_ENVIRONMENT.sh << 'EOF'" >> run.sh

         - declare -a STAGES="('INIT' 'DROP_TEST_BRANCH' 'EXIT')"
         - ENV_INFR_INIT="^BITBUCKET_|^BB_"

         - for stg in "${STAGES[@]}"; do
         -  if [ -f "./pipeline/proj_${stg,,}.sh" ]; then
         -   tmp_env="ENV_INFR_${stg}"
         -   if [ ! -z ${!tmp_env} ]; then
         -    venv=$(env -0 | grep -z -E "${!tmp_env}" | xargs -0 -n 1 echo)
         -    echo "$venv" >> run.sh
         -    unset venv
         -   fi
         -   tmp_env="ENV_VAR_${stg}"
         -   if [ ! -z ${!tmp_env} ]; then
         -    venv=$(env -0 | grep -z -E "${!tmp_env}" | sed -z 's/^\([a-zA-Z0-9_]*\)=\(.*\)/EVAR[\1]=\x27\2\x27\n/')
         -    echo "declare -A EVAR" >> run.sh
         -    echo "$venv" >> run.sh
         -    unset venv
         -   fi
         -   cat ./pipeline/proj_${stg,,}.sh >> run.sh
         -  fi
         - done

         - echo "EOF" >> run.sh
         - echo ". ./local_run_$BITBUCKET_DEPLOYMENT_ENVIRONMENT.sh" >> run.sh
         - cat run.sh
         - pipe:  atlassian/ssh-run:0.2.4
           variables:
            SSH_USER: $DEV_HOST_SSH_USER
            SSH_KEY: $DEV_KEY
            SERVER: $DEV_HOST
            PORT: $DEV_HOST_SSH_PORT
            MODE: 'script'
            COMMAND: "run.sh" 


   - step: &PRDeploy
        name: Pull Request Deployment 
        deployment: Test

        script: 
         - destfolder="$BITBUCKET_WORKSPACE/$BITBUCKET_DEPLOYMENT_ENVIRONMENT/$BITBUCKET_REPO_SLUG"
         - if [ ${BITBUCKET_DEPLOYMENT_ENVIRONMENT} == "test" -a ${BITBUCKET_BRANCH} == "master" ]; then
         -   echo "[[ -d $destfolder ]] || exit 0; cd $destfolder" > run.sh
         -   declare -a STAGES="('INIT' 'DROP_TEST_BRANCH' 'EXIT')"
         - else  
         -   echo "[[ -d $destfolder ]] || mkdir $destfolder; cd $destfolder" > run.sh
         -   tmp_stg="STAGE_${BITBUCKET_DEPLOYMENT_ENVIRONMENT^^}"
         -   declare -a STAGES="('INIT' ${!tmp_stg} 'EXIT')"
         - fi
         - echo "cat > local_run_$BITBUCKET_DEPLOYMENT_ENVIRONMENT.sh << 'EOF'" >> run.sh
         - ENV_INFR_INIT="^BITBUCKET_|^BB_"

         - for stg in "${STAGES[@]}"; do
         -  if [ -f "./pipeline/proj_${stg,,}.sh" ]; then
         -   tmp_env="ENV_INFR_${stg}"
         -   if [ ! -z ${!tmp_env} ]; then
         -    venv=$(env -0 | grep -z -E "${!tmp_env}" | xargs -0 -n 1 echo)
         -    echo "$venv" >> run.sh
         -    unset venv
         -   fi
         -   tmp_env="ENV_VAR_${stg}"
         -   if [ ! -z ${!tmp_env} ]; then
         -    venv=$(env -0 | grep -z -E "${!tmp_env}" | sed -z 's/^\([a-zA-Z0-9_]*\)=\(.*\)/EVAR[\1]=\x27\2\x27\n/')
         -    echo "declare -A EVAR" >> run.sh
         -    echo "$venv" >> run.sh
         -    unset venv
         -   fi
         -   cat ./pipeline/proj_${stg,,}.sh >> run.sh
         -  fi
         - done

         - echo "EOF" >> run.sh
         
         - if [ ! -z $PR_NOT_LAUNCH -a $BITBUCKET_BRANCH != $PR_NOT_LAUNCH ]; then
         -  echo ". ./local_run_$BITBUCKET_DEPLOYMENT_ENVIRONMENT.sh" >> run.sh
         - fi

         - cat run.sh
         - pipe:  atlassian/ssh-run:0.2.4
           variables:
            SSH_USER: $DEV_HOST_SSH_USER
            SSH_KEY: $DEV_KEY
            SERVER: $DEV_HOST
            PORT: $DEV_HOST_SSH_PORT
            MODE: 'script'
            COMMAND: "run.sh" 


pipelines:
# default: 
#  - step:
#     script:
#       - echo "run default, to do some work of CI"
#       - echo "nothing to do"

 pull-requests:
#    feature/pipeline: 
   '**':
    - step: 
       <<: *PRDeploy
       name: Merge PR & Build 
       deployment: Test

 branches: 
   master:
    - step:
#       <<: *Delete_test_branch
       <<: *PRDeploy
       name: Drop test branch
       deployment: Test
    - step: 
       <<: *PRDeploy
       name: Deployment master branch to Production
       deployment: Production


